package es.home.almacen.dto;

// Generated 11-mar-2011 12:03:37 by Hibernate Tools 3.3.0.GA

/**
 * Cancion generated by hbm2java
 */
public class CancionDTO implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private Integer idcancion;
    private DiscoDTO disco;
    private String nombre;
    private String duracion;

    public CancionDTO() {
    }

    public CancionDTO(DiscoDTO disco, String nombre) {
	this.disco = disco;
	this.nombre = nombre;
    }

    public CancionDTO(DiscoDTO disco, String nombre, String duracion) {
	this.disco = disco;
	this.nombre = nombre;
	this.duracion = duracion;
    }

    public DiscoDTO getDisco() {
	return this.disco;
    }

    public String getDuracion() {
	return this.duracion;
    }

    public Integer getIdcancion() {
	return this.idcancion;
    }

    public String getNombre() {
	return this.nombre;
    }

    public void setDisco(DiscoDTO disco) {
	this.disco = disco;
    }

    public void setDuracion(String duracion) {
	this.duracion = duracion;
    }

    public void setIdcancion(Integer idcancion) {
	this.idcancion = idcancion;
    }

    public void setNombre(String nombre) {
	this.nombre = nombre;
    }

}
