package es.home.almacen.dto;

// Generated 11-mar-2011 12:03:37 by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Disco generated by hbm2java
 */
public class DiscoDTO implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private Integer iddisco;
    private GrupoDTO grupo;
    private String nombre;
    private String productor;
    private String sello;
    private Integer anyo;
    private Set<CancionDTO> cancions = new HashSet<CancionDTO>(0);
    private Set<ParticipanteDTO> participantes = new HashSet<ParticipanteDTO>(0);

    public DiscoDTO() {
    }

    public DiscoDTO(GrupoDTO grupo, String nombre) {
	this.grupo = grupo;
	this.nombre = nombre;
    }

    public DiscoDTO(GrupoDTO grupo, String nombre, String productor, String sello, Integer anyo, Set<CancionDTO> cancions, Set<ParticipanteDTO> participantes) {
	this.grupo = grupo;
	this.nombre = nombre;
	this.productor = productor;
	this.sello = sello;
	this.anyo = anyo;
	this.cancions = cancions;
	this.participantes = participantes;
    }

    public Integer getAnyo() {
	return this.anyo;
    }

    public Set<CancionDTO> getCancions() {
	return this.cancions;
    }

    public GrupoDTO getGrupo() {
	return this.grupo;
    }

    public Integer getIddisco() {
	return this.iddisco;
    }

    public String getNombre() {
	return this.nombre;
    }

    public Set<ParticipanteDTO> getParticipantes() {
	return this.participantes;
    }

    public String getProductor() {
	return this.productor;
    }

    public String getSello() {
	return this.sello;
    }

    public void setAnyo(Integer anyo) {
	this.anyo = anyo;
    }

    public void setCancions(Set<CancionDTO> cancions) {
	this.cancions = cancions;
    }

    public void setGrupo(GrupoDTO grupo) {
	this.grupo = grupo;
    }

    public void setIddisco(Integer iddisco) {
	this.iddisco = iddisco;
    }

    public void setNombre(String nombre) {
	this.nombre = nombre;
    }

    public void setParticipantes(Set<ParticipanteDTO> participantes) {
	this.participantes = participantes;
    }

    public void setProductor(String productor) {
	this.productor = productor;
    }

    public void setSello(String sello) {
	this.sello = sello;
    }

}
