package es.home.almacen.dto;

// Generated 11-mar-2011 12:03:37 by Hibernate Tools 3.3.0.GA

/**
 * Participante generated by hbm2java
 */
public class ParticipanteDTO implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private Integer idplay;
    private ComponenteDTO componente;
    private DiscoDTO disco;
    private String instrumento;

    public ParticipanteDTO() {
    }

    public ParticipanteDTO(ComponenteDTO componente, DiscoDTO disco) {
	this.componente = componente;
	this.disco = disco;
    }

    public ParticipanteDTO(ComponenteDTO componente, DiscoDTO disco, String instrumento) {
	this.componente = componente;
	this.disco = disco;
	this.instrumento = instrumento;
    }

    public ComponenteDTO getComponente() {
	return this.componente;
    }

    public DiscoDTO getDisco() {
	return this.disco;
    }

    public Integer getIdplay() {
	return this.idplay;
    }

    public String getInstrumento() {
	return this.instrumento;
    }

    public void setComponente(ComponenteDTO componente) {
	this.componente = componente;
    }

    public void setDisco(DiscoDTO disco) {
	this.disco = disco;
    }

    public void setIdplay(Integer idplay) {
	this.idplay = idplay;
    }

    public void setInstrumento(String instrumento) {
	this.instrumento = instrumento;
    }

}
