package es.home.almacen.bean;

// Generated 11-mar-2011 12:03:37 by Hibernate Tools 3.3.0.GA

/**
 * Cancion generated by hbm2java
 */
public class Cancion implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private int idcancion;
    private Disco disco;
    private String nombre;
    private String duracion;

    public Cancion() {
	disco = new Disco();
    }

    public Cancion(Disco disco, String nombre) {
	this.disco = disco;
	this.nombre = nombre;
    }

    public Cancion(Disco disco, String nombre, String duracion) {
	this.disco = disco;
	this.nombre = nombre;
	this.duracion = duracion;
    }

    public Disco getDisco() {
	return this.disco;
    }

    public String getDuracion() {
	return this.duracion;
    }

    public int getIdcancion() {
	return this.idcancion;
    }

    public String getNombre() {
	return this.nombre;
    }

    public void setDisco(Disco disco) {
	this.disco = disco;
    }

    public void setDuracion(String duracion) {
	this.duracion = duracion;
    }

    public void setIdcancion(int idcancion) {
	this.idcancion = idcancion;
    }

    public void setNombre(String nombre) {
	this.nombre = nombre;
    }

}
