package es.home.almacen.bean;

// Generated 11-mar-2011 12:03:37 by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Disco generated by hbm2java
 */
public class Disco implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private int iddisco;
    private Grupo grupo;
    private String nombre;
    private String productor;
    private String sello;
    private int anyo;
    private Set<Cancion> cancions = new HashSet<Cancion>(0);
    private Set<Participante> participantes = new HashSet<Participante>(0);

    public Disco() {
	grupo = new Grupo();
    }

    public Disco(Grupo grupo, String nombre) {
	this.grupo = grupo;
	this.nombre = nombre;
    }

    public Disco(Grupo grupo, String nombre, String productor, String sello, int anyo, Set<Cancion> cancions, Set<Participante> participantes) {
	this.grupo = grupo;
	this.nombre = nombre;
	this.productor = productor;
	this.sello = sello;
	this.anyo = anyo;
	this.cancions = cancions;
	this.participantes = participantes;
    }

    public int getAnyo() {
	return this.anyo;
    }

    public Set<Cancion> getCancions() {
	return this.cancions;
    }

    public Grupo getGrupo() {
	return this.grupo;
    }

    public int getIddisco() {
	return this.iddisco;
    }

    public String getNombre() {
	return this.nombre;
    }

    public Set<Participante> getParticipantes() {
	return this.participantes;
    }

    public String getProductor() {
	return this.productor;
    }

    public String getSello() {
	return this.sello;
    }

    public void setAnyo(int anyo) {
	this.anyo = anyo;
    }

    public void setCancions(Set<Cancion> cancions) {
	this.cancions = cancions;
    }

    public void setGrupo(Grupo grupo) {
	this.grupo = grupo;
    }

    public void setIddisco(int iddisco) {
	this.iddisco = iddisco;
    }

    public void setNombre(String nombre) {
	this.nombre = nombre;
    }

    public void setParticipantes(Set<Participante> participantes) {
	this.participantes = participantes;
    }

    public void setProductor(String productor) {
	this.productor = productor;
    }

    public void setSello(String sello) {
	this.sello = sello;
    }

}
