package es.home.almacen.bean;

// Generated 11-mar-2011 12:03:37 by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Grupo generated by hbm2java
 */
public class Grupo implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private int idgrupo;
    private String nombre;
    private Set<Disco> discos = new HashSet<Disco>(0);

    public Grupo() {
    }

    public Grupo(String nombre) {
	this.nombre = nombre;
    }

    public Grupo(String nombre, Set<Disco> discos) {
	this.nombre = nombre;
	this.discos = discos;
    }

    public Set<Disco> getDiscos() {
	return this.discos;
    }

    public int getIdgrupo() {
	return this.idgrupo;
    }

    public String getNombre() {
	return this.nombre;
    }

    public void setDiscos(Set<Disco> discos) {
	this.discos = discos;
    }

    public void setIdgrupo(int idgrupo) {
	this.idgrupo = idgrupo;
    }

    public void setNombre(String nombre) {
	this.nombre = nombre;
    }

}
