package es.home.almacen.bean;

// Generated 11-mar-2011 12:03:37 by Hibernate Tools 3.3.0.GA

/**
 * Libro generated by hbm2java
 */
public class Libro implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private int idlibro;
    private String nombre;
    private String nombreOriginal;
    private String autor;
    private String ilustracion;
    private String disenyo;
    private String traduccion;
    private String editorial;
    private String edicion;
    private int paginas;
    private String argumento;
    private String saga;

    public Libro() {
    }

    public Libro(int idlibro, String nombre, String autor) {
	this.idlibro = idlibro;
	this.nombre = nombre;
	this.autor = autor;
    }

    public Libro(int idlibro, String nombre, String nombreOriginal, String autor, String ilustracion, String disenyo, String traduccion, String editorial,
	    String edicion, int paginas, String argumento, String saga) {
	this.idlibro = idlibro;
	this.nombre = nombre;
	this.nombreOriginal = nombreOriginal;
	this.autor = autor;
	this.ilustracion = ilustracion;
	this.disenyo = disenyo;
	this.traduccion = traduccion;
	this.editorial = editorial;
	this.edicion = edicion;
	this.paginas = paginas;
	this.argumento = argumento;
	this.saga = saga;
    }

    public String getArgumento() {
	return this.argumento;
    }

    public String getAutor() {
	return this.autor;
    }

    public String getDisenyo() {
	return this.disenyo;
    }

    public String getEdicion() {
	return this.edicion;
    }

    public String getEditorial() {
	return this.editorial;
    }

    public int getIdlibro() {
	return this.idlibro;
    }

    public String getIlustracion() {
	return this.ilustracion;
    }

    public String getNombre() {
	return this.nombre;
    }

    public String getNombreOriginal() {
	return this.nombreOriginal;
    }

    public int getPaginas() {
	return this.paginas;
    }

    public String getSaga() {
	return this.saga;
    }

    public String getTraduccion() {
	return this.traduccion;
    }

    public void setArgumento(String argumento) {
	this.argumento = argumento;
    }

    public void setAutor(String autor) {
	this.autor = autor;
    }

    public void setDisenyo(String disenyo) {
	this.disenyo = disenyo;
    }

    public void setEdicion(String edicion) {
	this.edicion = edicion;
    }

    public void setEditorial(String editorial) {
	this.editorial = editorial;
    }

    public void setIdlibro(int idlibro) {
	this.idlibro = idlibro;
    }

    public void setIlustracion(String ilustracion) {
	this.ilustracion = ilustracion;
    }

    public void setNombre(String nombre) {
	this.nombre = nombre;
    }

    public void setNombreOriginal(String nombreOriginal) {
	this.nombreOriginal = nombreOriginal;
    }

    public void setPaginas(int paginas) {
	this.paginas = paginas;
    }

    public void setSaga(String saga) {
	this.saga = saga;
    }

    public void setTraduccion(String traduccion) {
	this.traduccion = traduccion;
    }

}
