package es.home.almacen.bean;

// Generated 11-mar-2011 12:03:37 by Hibernate Tools 3.3.0.GA

/**
 * Participante generated by hbm2java
 */
public class Participante implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private int idplay;
    private Componente componente;
    private Disco disco;
    private String instrumento;

    public Participante() {
	componente = new Componente();
	disco = new Disco();
    }

    public Participante(Componente componente, Disco disco) {
	this.componente = componente;
	this.disco = disco;
    }

    public Participante(Componente componente, Disco disco, String instrumento) {
	this.componente = componente;
	this.disco = disco;
	this.instrumento = instrumento;
    }

    public Componente getComponente() {
	return this.componente;
    }

    public Disco getDisco() {
	return this.disco;
    }

    public int getIdplay() {
	return this.idplay;
    }

    public String getInstrumento() {
	return this.instrumento;
    }

    public void setComponente(Componente componente) {
	this.componente = componente;
    }

    public void setDisco(Disco disco) {
	this.disco = disco;
    }

    public void setIdplay(int idplay) {
	this.idplay = idplay;
    }

    public void setInstrumento(String instrumento) {
	this.instrumento = instrumento;
    }

}
